### ISSUE TITLE
Node abgeschossen

### ISSUE THREAD

**Issue by wallenium** [stfnhmplr/node-red-contrib-homee#2]
Hallo Stefan,
irgendwie habe ich es geschafft, Node Red abzuschiessen:

```
3 Nov 22:29:33 - [info] Node-RED version: v1.0.2
3 Nov 22:29:33 - [info] Node.js  version: v10.17.0
3 Nov 22:29:33 - [info] Linux 4.19.75-v7+ arm LE
3 Nov 22:29:34 - [info] Loading palette nodes
3 Nov 22:29:37 - [info] Settings file  : /home/pi/.node-red/settings.js
3 Nov 22:29:37 - [info] Context store  : 'default' [module=memory]
3 Nov 22:29:37 - [info] User directory : /home/pi/.node-red
3 Nov 22:29:37 - [warn] Projects disabled : editorTheme.projects.enabled=false
3 Nov 22:29:37 - [info] Flows file     : /home/pi/.node-red/flows_raspberrypi.json
3 Nov 22:29:37 - [info] Starting flows
3 Nov 22:29:37 - [error] [homeeDevice:1d3a6c50.e7c13c] SyntaxError: Unexpected token , in JSON at position 331
3 Nov 22:29:37 - [info] Started flows
3 Nov 22:29:37 - [info] Server now running at http://127.0.0.1:1880/
3 Nov 22:29:40 - [red] Uncaught Exception:
3 Nov 22:29:40 - TypeError: Cannot read property 'device' of null
    at RED.nodes.eachNode (/home/pi/.node-red/node_modules/node-red-contrib-homee/nodes/virtualHomee.js:33:40)
    at Object.eachNode (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:227:13)
    at Timeout.VirtualHomeeNode.setTimeout [as _onTimeout] (/home/pi/.node-red/node_modules/node-red-contrib-homee/nodes/virtualHomee.js:30:17)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Service RestartSec=100ms expired, scheduling restart.
nodered.service: Scheduled restart job, restart counter is at 21.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.
```
wie genau ich das geschafft habe weiss ich nicht. Eventuell eckige Klammern vergessen in der config. Kann leider nicht mehr nachsehen.

**Comment by wallenium** [comment]
waren fehlende [] unf vor allem ein , am Schluss. ich weiss nicht ob es abgefangen werden kann.

**Comment by 0815nils** [comment]
habe das gleiche. 
kommt bei mir allerdings sobald ich ein device anlege und erstmalig deploye.
führt zu konstanten node-red Neustarts.

**Comment by wallenium** [comment]
> waren fehlende [] und vor allem ein , am Schluss. ich weiss nicht ob es abgefangen werden kann.
Ich habe hier die JSON editiert. Danach ging es. In der neuen Beta wird das abgefangen.
